<a href="https://colab.research.google.com/github/Vishvesh-Bhardwaj/Machine-Learning-Core-Concepts/blob/main/Classification_KNN%2C_SVM%2C_NB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

# Load the dataset
data = pd.read_csv('https://raw.githubusercontent.com/Vishvesh-Bhardwaj/Machine-Learning-Core-Concepts/main/diabetes-_1_.csv')

# Print the first 5 rows of the dataset
print(data.head())


   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  


In [4]:
from sklearn.model_selection import train_test_split

X = data.drop('Outcome', axis=1)
y = data['Outcome']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


In [5]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Create the KNN model
knn = KNeighborsClassifier(n_neighbors=5)

# Train the model using the training data
knn.fit(X_train, y_train)

# Predict the classes of the testing data
y_pred = knn.predict(X_test)

# Print the confusion matrix
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

# Print the accuracy score
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

# Print the precision score
precision = precision_score(y_test, y_pred)
print('Precision:', precision)

# Print the recall score
recall = recall_score(y_test, y_pred)
print('Recall:', recall)

# Print the specificity score


Confusion Matrix:
[[114  37]
 [ 35  45]]
Accuracy: 0.6883116883116883
Precision: 0.5487804878048781
Recall: 0.5625


In [6]:
# Calculate the specificity score
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
specificity = tn / (tn + fp)
print('Specificity:', specificity)

# Print the F1 score
f1 = f1_score(y_test, y_pred)
print('F1 Score:', f1)


Specificity: 0.7549668874172185
F1 Score: 0.5555555555555556


In [7]:
from sklearn.svm import SVC

# Create the SVM model
svm = SVC(kernel='linear')

# Train the model using the training data
svm.fit(X_train, y_train)

# Predict the classes of the testing data
y_pred = svm.predict(X_test)

# Print the confusion matrix
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

# Print the accuracy score
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

# Print the precision score
precision = precision_score(y_test, y_pred)
print('Precision:', precision)

# Print the recall score
recall = recall_score(y_test, y_pred)
print('Recall:', recall)

# Calculate the specificity score
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
specificity = tn / (tn + fp)
print('Specificity:', specificity)

# Print the F1 score
f1 = f1_score(y_test, y_pred)
print('F1 Score:', f1)


Confusion Matrix:
[[122  29]
 [ 30  50]]
Accuracy: 0.7445887445887446
Precision: 0.6329113924050633
Recall: 0.625
Specificity: 0.8079470198675497
F1 Score: 0.6289308176100629


In [8]:
from sklearn.naive_bayes import GaussianNB

# Create the NB model
nb = GaussianNB()

# Train the model using the training data
nb.fit(X_train, y_train)

# Predict the classes of the testing data
y_pred = nb.predict(X_test)

# Print the confusion matrix
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

# Print the accuracy score
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

# Print the precision score
precision = precision_score(y_test, y_pred)
print('Precision:', precision)

# Print the recall score
recall = recall_score(y_test, y_pred)
print('Recall:', recall)

# Calculate the specificity score
tn, fp,fn, tp = confusion_matrix(y_test, y_pred).ravel()
specificity = tn / (tn + fp)
print('Specificity:', specificity)

f1 = f1_score(y_test, y_pred)
print('F1 Score:', f1)


Confusion Matrix:
[[119  32]
 [ 27  53]]
Accuracy: 0.7445887445887446
Precision: 0.6235294117647059
Recall: 0.6625
Specificity: 0.7880794701986755
F1 Score: 0.6424242424242423
